---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "Functional Tests"
# REQUIRED SECRETS (must be defined in repository secrets):
#   RTD_TOKEN          -> Populates [rtd] token
#   READ_GITHUB_TOKEN  -> Populates [github] token
#                         (read-only scope sufficient for listing)
#   NEXUS2_PASSWORD    -> Populates nexus.onap.org password
#                         (user assumed 'admin' unless overridden)
#   NEXUS3_PASSWORD    -> Populates nexus3.onap.org password
#                         (user assumed 'modesevenindustrialsolutions2')
#
# Secrets injected into ephemeral lftools.ini for functional tests.
# DO NOT commit real credentials. Generated per run inside the workflow.

"on":
  workflow_dispatch:
    inputs:
      test_category:
        description: 'Test categories to run (comma-separated: 1,2,3)'
        required: false
        default: '1'
        type: string
      test_filter:
        description: 'Test filter substring (e.g., jenkins, ldap, nexus)'
        required: false
        default: ''
        type: string
      verbose:
        description: 'Enable verbose output'
        required: false
        default: false
        type: boolean
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'lftools_uv/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'scripts/run_functional_tests.sh'
      - '.github/workflows/functional-tests.yaml'
  schedule:
    # Daily at 06:00 UTC (after dependency updates)
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  functional-test-matrix:
    name: "Functional Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          # Core functionality (fast)
          - test_filter: "core"
            description: "Core CLI functionality"
            category: "1"

          # Help screens (fast)
          - test_filter: "help"
            description: "CLI help screens"
            category: "1"

          # Jenkins integration (requires external services)
          - test_filter: "jenkins"
            description: "Jenkins integration"
            category: "1"

          # Python-LDAP modernization validation
          - test_filter: "ldap"
            description: "LDAP modernization"
            category: "1"

          # Nexus integration (external services)
          - test_filter: "nexus"
            description: "Nexus repository integration"
            category: "1"

          # OpenStack integration (external services)
          - test_filter: "openstack"
            description: "OpenStack integration"
            category: "1"

          # GitHub integration (external services)
          - test_filter: "github"
            description: "GitHub integration"
            category: "1"

    env:
      TEST_CATEGORY: ${{ inputs.test_category || matrix.category }}
      TEST_FILTER: ${{ inputs.test_filter || matrix.test_filter }}
      VERBOSE: ${{ inputs.verbose && '1' || '0' }}
      OUTPUT_FORMAT: "json"
      # Environment variables for external service testing
      JENKINS_URL: "https://jenkins.onap.org/"
      NEXUS2_FQDN: "nexus.onap.org"
      NEXUS3_FQDN: "nexus3.onap.org"
      GITHUB_ORG: "onap"
      OS_CLOUD: "devstack"

    steps:
      - name: "Harden Runner"
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: "Checkout"
        # yamllint disable-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Generate lftools.ini from secrets"
        shell: bash
        env:
          RTD_TOKEN: "${{ secrets.RTD_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.READ_GITHUB_TOKEN }}"
          NEXUS2_PASSWORD: "${{ secrets.NEXUS2_PASSWORD }}"
          NEXUS3_PASSWORD: "${{ secrets.NEXUS3_PASSWORD }}"
        run: |
          set -euo pipefail
          CONFIG_DIR="${HOME}/.config/lftools"
          mkdir -p "${CONFIG_DIR}"
          INI_FILE="${CONFIG_DIR}/lftools.ini"

          echo "# Ephemeral lftools.ini (functional-tests job)" > "${INI_FILE}"
          echo "# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> "${INI_FILE}"

          # [rtd] section
          if [[ -n "${RTD_TOKEN:-}" ]]; then
            {
              echo "[rtd]"
              echo "token = ${RTD_TOKEN}"
              echo "endpoint = https://readthedocs.org/api/v3/"
              echo
            } >> "${INI_FILE}"
          fi

            # [github] section
          if [[ -n "${GITHUB_TOKEN:-}" ]]; then
            {
              echo "[github]"
              echo "token = ${GITHUB_TOKEN}"
              echo
            } >> "${INI_FILE}"
          fi

          # nexus.onap.org (Nexus2)
          if [[ -n "${NEXUS2_PASSWORD:-}" ]]; then
            {
              echo "[nexus.onap.org]"
              echo "username = admin"
              echo "password = ${NEXUS2_PASSWORD}"
              echo "endpoint = https://nexus.onap.org/"
              echo
            } >> "${INI_FILE}"
          fi

          # nexus3.onap.org (Nexus3)
          if [[ -n "${NEXUS3_PASSWORD:-}" ]]; then
            {
              echo "[nexus3.onap.org]"
              echo "username = modesevenindustrialsolutions2"
              echo "password = ${NEXUS3_PASSWORD}"
              echo "endpoint = https://nexus3.onap.org/"
              echo
            } >> "${INI_FILE}"
          fi

          echo "Generated lftools.ini with sections:"
          grep '^[[]' "${INI_FILE}" || true

      - name: "Install uv"
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        run: uv python install

      - name: "Sync dependencies"
        run: uv sync --all-extras

      - name: "Run functional tests: ${{ matrix.description }}"
        id: functional-tests
        run: |
          set -euo pipefail

          # Create results directory
          mkdir -p functional-test-results

          # Use environment variables already set by workflow
          # TEST_CATEGORY and TEST_FILTER are already set in env section
          export OUTPUT_FORMAT="json"
          export VERBOSE="1"

          # Debug essential information
          echo "Running functional tests with filter: ${TEST_FILTER:-none}"
          echo "Test category: ${TEST_CATEGORY}"

          # Make script executable (in case it's not)
          chmod +x scripts/run_functional_tests.sh

          # Run tests with proper output separation
          # Stderr goes to console, stdout (JSON) goes to file
          if ./scripts/run_functional_tests.sh \
              > functional-test-results/results.json; then
            echo "exit_code=0" >> "$GITHUB_OUTPUT"
            echo "Test execution completed successfully"
          else
            exit_code=$?
            echo "exit_code=1" >> "$GITHUB_OUTPUT"
            echo "Test execution failed with exit code: $exit_code"

            # Show some debug info on failure
            if [[ -f functional-test-results/results.json ]]; then
              file_size=$(wc -c < functional-test-results/results.json)
              echo "Results file exists (${file_size} bytes)"
            else
              echo "No results file generated"
            fi
          fi

          # Extract summary for step output
          if [[ -f functional-test-results/results.json ]]; then
            {
              echo "## Functional Test Results: ${{ matrix.description }}"
              echo ""
            } >> "$GITHUB_STEP_SUMMARY"

            # Parse JSON properly using jq-style extraction or grep
            # Extract test counts from actual JSON structure
            total=$(grep -o '"total":[0-9]*' \
              functional-test-results/results.json | \
              grep -o '[0-9]*' || echo "0")
            passed=$(grep -o '"passed":[0-9]*' \
              functional-test-results/results.json | \
              grep -o '[0-9]*' || echo "0")
            failed=$(grep -o '"failed":[0-9]*' \
              functional-test-results/results.json | \
              grep -o '[0-9]*' || echo "0")
            skipped=$(grep -o '"skipped":[0-9]*' \
              functional-test-results/results.json | \
              grep -o '[0-9]*' || echo "0")

            {
              echo "- **Total Tests**: $total"
              echo "- **Passed**: ✅ $passed"
              echo "- **Failed**: ❌ $failed"
              echo "- **Skipped**: ⏭️ $skipped"
              echo ""
            } >> "$GITHUB_STEP_SUMMARY"

            if [[ "$failed" -gt 0 ]]; then
              echo "❌ Some tests failed. Check logs for details." \
                >> "$GITHUB_STEP_SUMMARY"
            elif [[ "$passed" -gt 0 ]]; then
              echo "✅ All tests passed!" >> "$GITHUB_STEP_SUMMARY"
            else
              echo "⚠️ No tests were executed." >> "$GITHUB_STEP_SUMMARY"
            fi
          else
            echo "⚠️ No test results file found." >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: "Upload test results"
        if: always()
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: functional-test-results-${{ matrix.test_filter }}
          path: |
            functional-test-results/
            .functional_logs/
          retention-days: 7
          if-no-files-found: warn

      - name: "Fail job if tests failed"
        if: steps.functional-tests.outputs.exit_code != '0'
        run: |
          echo "Functional tests failed for filter: ${{ matrix.test_filter }}"
          exit 1

  # Aggregate results job
  functional-test-summary:
    name: "Functional Test Summary"
    runs-on: ubuntu-latest
    needs: functional-test-matrix
    if: always()
    timeout-minutes: 5
    steps:
      - name: "Check matrix results"
        run: |
          {
            echo "## Overall Functional Test Results"
            echo ""
          } >> "$GITHUB_STEP_SUMMARY"

          # Check if any jobs failed
          matrix_result="${{ needs.functional-test-matrix.result }}"
          if [[ "$matrix_result" == "failure" ]]; then
            {
              echo "❌ Some functional test categories failed."
              echo ""
              echo "Please check the individual job results above for details."
            } >> "$GITHUB_STEP_SUMMARY"
            exit 1
          elif [[ "$matrix_result" == "success" ]]; then
            {
              echo "✅ All functional test categories passed!"
              echo ""
              echo "The CLI functionality is working correctly across all"
              echo "tested categories."
            } >> "$GITHUB_STEP_SUMMARY"
          else
            {
              echo "⚠️ Some functional tests were cancelled or skipped."
            } >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

  # Security and compliance check (Category 1 tests only)
  security-baseline:
    name: "Security Baseline Check"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Harden Runner"
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: "Checkout"
        # yamllint disable-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Generate lftools.ini from secrets"
        shell: bash
        env:
          RTD_TOKEN: "${{ secrets.RTD_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.READ_GITHUB_TOKEN }}"
          NEXUS2_PASSWORD: "${{ secrets.NEXUS2_PASSWORD }}"
          NEXUS3_PASSWORD: "${{ secrets.NEXUS3_PASSWORD }}"
        run: |
          set -euo pipefail
          CONFIG_DIR="${HOME}/.config/lftools"
          mkdir -p "${CONFIG_DIR}"
          INI_FILE="${CONFIG_DIR}/lftools.ini"
          {
            echo "# Ephemeral lftools.ini (security-baseline job)"
            echo "# Generated by workflow (security-baseline)"
            echo "# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          } > "${INI_FILE}"

          if [[ -n "${RTD_TOKEN:-}" ]]; then
            {
              echo "[rtd]"
              echo "token = ${RTD_TOKEN}"
              echo "endpoint = https://readthedocs.org/api/v3/"
              echo
            } >> "${INI_FILE}"
          fi

          if [[ -n "${GITHUB_TOKEN:-}" ]]; then
            {
              echo "[github]"
              echo "token = ${GITHUB_TOKEN}"
              echo
            } >> "${INI_FILE}"
          fi

          if [[ -n "${NEXUS2_PASSWORD:-}" ]]; then
            {
              echo "[nexus.onap.org]"
              echo "username = admin"
              echo "password = ${NEXUS2_PASSWORD}"
              echo "endpoint = https://nexus.onap.org/"
              echo
            } >> "${INI_FILE}"
          fi

          if [[ -n "${NEXUS3_PASSWORD:-}" ]]; then
            {
              echo "[nexus3.onap.org]"
              echo "username = modesevenindustrialsolutions2"
              echo "password = ${NEXUS3_PASSWORD}"
              echo "endpoint = https://nexus3.onap.org/"
              echo
            } >> "${INI_FILE}"
          fi

          echo "Generated sections:"
          grep '^[[]' "${INI_FILE}" || true

      - name: "Install uv"
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: true

      - name: "Security check: No Category 2/3 tests in default run"
        run: |
          # Ensure that only Category 1 (harmless) tests run by default
          if grep -E ":::[23]:::" scripts/run_functional_tests.sh | \
              grep -v "^#"; then
            {
              echo "❌ Found uncommented Category 2 or 3 tests in"
              echo "functional test script!"
              echo "Only Category 1 (harmless/read-only) tests should be"
              echo "enabled by default."
            }
            exit 1
          else
            echo "✅ Only Category 1 (harmless) tests are enabled by"
            echo "default."
          fi

      - name: "Dependency audit"
        run: |
          uv python install
          uv sync --all-extras
          # Run basic security checks on the environment for functional tests
          uv run python3 -c "
          import sys
          print(f'Python version: {sys.version}')

          # Check that our modernized dependencies are properly installed
          try:
              import ldap
              print(f'python-ldap version: {ldap.__version__}')
              from packaging import version
              if version.parse(ldap.__version__) >= \
                  version.parse('3.4.0'):
                  print('✅ python-ldap modernization verified')
              else:
                  print('❌ python-ldap version too old')
                  sys.exit(1)
          except ImportError:
              print('⚠️ python-ldap not installed (ldap extra not used)')

          print('✅ Dependency audit passed')
          "
