---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: 'Audit GitHub Action Calls'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths: ['.github/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify:
    name: Verify
    # yamllint disable-line rule:line-length
    uses: lfit/releng-reusable-workflows/.github/workflows/reuse-verify-github-actions.yaml@aa120f2c452e600b606d6a646baa9e8ca4dfc294 # v0.2.23
    permissions:
      contents: read
